### ISSUE TITLE
Serialization by "Generic Object Serializer" of classes after modification of private data

### ISSUE THREAD

**Issue by klopsquark** [LogMANOriginal/JSONtext-Object-Serialization#18]
Hello,

I noticed something else. I experimented a little with the library and found that there might be a problem if you make changes to the private data of a class in an existing class hierarchy. So when you add or remove a property.

It actually also relates to "LabVIEW-Composition" but has an impact to this lib.

The first noticeable error was thrown at this point:

![image](https://user-images.githubusercontent.com/23039409/118253833-aa53f100-b4aa-11eb-827c-cf8eba7aafba.png)

![image](https://user-images.githubusercontent.com/23039409/118254177-19314a00-b4ab-11eb-880a-0944438f5936.png)

Upon closer inspection, I noticed an error thrown earlier:

![image](https://user-images.githubusercontent.com/23039409/118254615-9066de00-b4ab-11eb-8358-ddb7a997430f.png)

at this location:

![image](https://user-images.githubusercontent.com/23039409/118254721-affe0680-b4ab-11eb-902f-88110225f64b.png)

This error can vary somewhat depending on how you are trying to fix it.

If certain elements are changed in LabVIEW (libraries, classes, etc.), a so-called mutation history is maintained. The elements still know their "changes" to previous versions. The latest version is then probably always in the memory.

I suspect that there is an error in the order of the versions when assembling the type descriptor.

The following seems to fix the problem.

![image](https://user-images.githubusercontent.com/23039409/118255444-93160300-b4ac-11eb-8159-425f9b11de0a.png)

However, I am not 100% sure.

You can also manually delete the mutation history in the XML file of the class or use a LabVIEW internal VI.

![image](https://user-images.githubusercontent.com/23039409/118256132-70381e80-b4ad-11eb-8c28-d33df2289d5f.png)

Best regards...

**Comment by logmanoriginal** [comment]
Confirmed. This is clearly an oversight in the underlying library.

> If certain elements are changed in LabVIEW (libraries, classes, etc.), a so-called mutation history is maintained. The elements still know their "changes" to previous versions. The latest version is then probably always in the memory.
>
>I suspect that there is an error in the order of the versions when assembling the type descriptor.

LabVIEW stores version numbers [in reverse order of cluster data](https://labviewwiki.org/wiki/LabVIEW_Object#VersionList), which I wanted to hide from users. Turns out that I forgot to reverse the order at the end. It works as long as the version number of the child is smaller than or equal to the parent (because LabVIEW mutates history) but as soon as the number exceeds the limit, it breaks.

Anyway, your solution is correct.

**Comment by logmanoriginal** [comment]
I updated the library and build a new package:
https://github.com/LogMANOriginal/LabVIEW-Composition/releases/tag/untagged-ad8c76c43ab6e2eeb40b

Let me know if this works for you.

**Comment by klopsquark** [comment]
Hi,

I was busy during the last days. It seems so that I can not open the link to your new package. (page not found) Is it also available in the JKI package manager?

Best regards

**Comment by logmanoriginal** [comment]
My bad. I forgot that draft releases are not public. Here is a pre-release:
https://github.com/LogMANOriginal/LabVIEW-Composition/releases/tag/1.2.1

> Is it also available in the JKI package manager?

Not yet. The process takes a while and I would like to get your feedback first.

**Comment by klopsquark** [comment]
I have tested your modifications and it works now as far as I can see. Thank you very much.
