### ISSUE TITLE
Error when deserializing classes with no private data

### ISSUE THREAD

**Issue by derek-noreen** [LogMANOriginal/JSONtext-Object-Serialization#21]
Hello,
I am seeing an error returned when I try to unflatten a JSON created from a class that has an empty private data cluster in its hierarchy:
![image](https://user-images.githubusercontent.com/60997684/163075293-eee9ef63-ec65-422b-b3d4-8b6cc2cee290.png)

I can resolve the error by bypassing the JSON unflatten when the decomposed cluster contains 0 elements:
![image](https://user-images.githubusercontent.com/60997684/163075044-2fb1b519-78de-49d8-904c-66d3953fd7f6.png)

The origin of the error appears to be JSONtext.lvlib not being able to handle empty clusters:
![image](https://user-images.githubusercontent.com/60997684/163075536-543d570d-3de0-42af-93ae-20858025554a.png)

[zip containing test code to recreate error](https://github.com/LogMANOriginal/JSONtext-Object-Serialization/files/8477201/ChildWithoutData.zip)

**Comment by logmanoriginal** [comment]
Thanks for reporting and for providing test code. I'm surprised the type is detected as Cluster instead of Void, but that could be a side-effect of having all private data clusters in an array.

**Comment by logmanoriginal** [comment]
This is fixed in the main branch. Thanks again for reporting!

**Comment by derek-noreen** [comment]
Thanks for the fix! I love this package.
